# Clinical Explorer demo — local launcher.
#
# Deserializes the bundled board JSON (the same demo shown at R/Medicine 2026)
# and serves it. Run with:
#
#   source(system.file("examples/clinical-explorer.R", package = "blockr.pharma"))

pkgload::load_all("blockr.core")
pkgload::load_all("blockr.dock")
pkgload::load_all("blockr.dag")
pkgload::load_all("blockr.dplyr")
pkgload::load_all("blockr.ggplot")
pkgload::load_all("blockr.io")
pkgload::load_all("blockr.viz")
pkgload::load_all("blockr.dm")
pkgload::load_all("blockr.pharma")
pkgload::load_all("blockr.extra")
pkgload::load_all("blockr.session")

# The board's `data` block rebuilds its dm from safetyData (the ADaM example
# tables adsl/adae/adlbc/advs), so that package must be installed.
library("safetyData")

# The pinned demo board references blocks from the packages loaded above, so
# they must be attached for blockr_deser() to find their constructors. The
# board is regenerated by dev/regenerate-clinical-explorer.R -- keep the two
# in sync when blocks are added or swapped.

options(
  blockr.dock_is_locked = FALSE,
  blockr.eval_parent_env = asNamespace("stats"),
  # blockr.session: build the board from the request URL (board_name / user /
  # version handle) so named projects are shareable / bookmarkable.
  blockr.session_url_params = TRUE
)

# blockr.session drives project management: `manage_project()` adds the
# save / load / share plugin (the served demo board stays visible on a cold
# load; users save named projects on top of it). The default backend is a
# local pins board (pins::board_local()) off Posit Connect, so this works
# as-is locally. NB: do NOT pair with `rack_loader()` here -- that loader
# clears the board on a handle-less cold load, which would hide the demo.
plugins <- list(manage_project())
if (requireNamespace("blockr.ai", quietly = TRUE)) {
  library(blockr.ai)
  plugins <- c(plugins, list(ai_ctrl_block()))
}

json_path <- system.file(
  "examples/clinical-explorer.json",
  package = "blockr.pharma"
)
stopifnot(nzchar(json_path))

dashboard_json <- jsonlite::fromJSON(
  json_path,
  simplifyDataFrame = FALSE,
  simplifyMatrix = FALSE
)

board <- blockr.core::blockr_deser(dashboard_json)

serve(
  board,
  plugins = custom_plugins(plugins)
)
